baseurl = "/"
languageCode = "en-us"
title = "Dongsheng Deng's homepage"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    posts = "/posts/:year-:month/:slug/"
    note = "/note/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Resource"
    url = "/resource/"
    weight = 3
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 5

[params]
    description = "Dongsheng Deng's homepage"
    footer = "&copy; [Dongsheng Deng](https://ddswhu.me/) 2018 -- 2020 Theme [XMin](https://themes.gohugo.io/hugo-xmin/) Powered by Hugo and Netlify"
